services: 
  frontend:
    image: node
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - ./entrypoint.sh:/app/entrypoint.sh
    working_dir: /app
    entrypoint: ["/app/entrypoint.sh"]
    

    # TODO: créer un service pour lancer le backend 
    # backend:

    # TODO: créer un service pour lancer la base de données
    # database: