services:
  #frontend a lancer via npm en local.
  api:
    container_name: api
    build:
      context: ./services/api
      dockerfile: Dockerfile
      target: ${NODE_ENV:-dev}
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - ./services/api:/app
    depends_on:
      database:
        condition: service_started
      rabbitmq:
        condition: service_healthy

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672" # dashboard
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 10s
      timeout: 10s
      retries: 5

  file-parser:
    build:
      context: ./services/file-parser
      dockerfile: Dockerfile
      target: ${NODE_ENV:-dev}
    volumes:
      - ./services/file-parser:/app
    env_file: ".env"
    depends_on:
      rabbitmq:
        condition: service_healthy

  quiz-generator:
    build:
      context: ./services/quiz-generator
      dockerfile: Dockerfile
      target: ${NODE_ENV:-dev}
    volumes:
      - ./services/quiz-generator:/app
    env_file: ".env"
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
      - "9090:9090"

  prometheus:
    image: prom/prometheus
    volumes:
      - ./services/metrics/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9091:9090" # localhost:9091 -> prometheus web UI

  grafana:
    image: grafana/grafana
    ports:
      - "9092:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus

  database:
    container_name: database
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=api

  matamo:
    image: matomo:latest
    ports:
      - "8080:80"
    env_file: ".env"
    volumes:
      - matomo-data:/var/www/html/matomo

volumes:
  grafana-storage:
  mongo-data:
  matomo-data:
