kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraMounts:
      - hostPath: /var/lib/longhorn/ctrl-plane
        containerPath: /var/lib/longhorn
  - role: worker
    extraMounts:
      - hostPath: /var/lib/longhorn/worker1
        containerPath: /var/lib/longhorn
  - role: worker
    extraMounts:
      - hostPath: /var/lib/longhorn/worker2
        containerPath: /var/lib/longhorn

