apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: mongodb
  namespace: mongodb
spec:
  members: 2
  type: ReplicaSet
  version: "8.0.10"
  users:
    - name: admin
      db: admin
      passwordSecretRef:
        name: admin-user
      roles:
        - name: root
          db: admin
      scramCredentialsSecretName: my-scram
  security:
#    tls:
#      enabled: true
#      certificateKeySecretRef:
#        name: mongodb-cert
#      caCertificateSecretRef:
#        name: mongodb-cert
#      # optional: true
    authentication:
      modes:
        - SCRAM
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib
  statefulSet:
    spec:
      template:
        spec:
          containers:
            - name: mongod
              resources:
                limits:
                  cpu: 800m
                  memory: 700Mi
                requests:
                  cpu: 200m
                  memory: 500Mi
      volumeClaimTemplates:
        - metadata:
            name: data-volume
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 5G