apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - analytics.revision-ai.com
        - revision-ai.com
        - api.revision-ai.com
      secretName: revision-ai-com-tls
  rules:
    - host: revision-ai.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-nginx-service
                port:
                  number: 8081
    - host: api.revision-ai.com
      http:
        paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: api-service
                  port:
                    number: 3000
    - host: analytics.revision-ai.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: matomo-service
                port:
                  number: 8080