apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rabbitmq-servicemonitor
  labels:
    release: prometheus  # adapte selon ton label Prometheus
spec:
  jobLabel: rabbitmq
  selector:
    matchLabels:
      "app.kubernetes.io/component": rabbitmq
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: prometheus  # service port name in rabbitmq svc
      interval: 30s
      path: /metrics