apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: matomo-deploy
  name: matamo-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matomo-deploy
  strategy: {}
  template:
    metadata:
      labels:
        app: matomo-deploy
        debug: "true"
    spec:
      containers:
        - image: matomo:latest
          imagePullPolicy: IfNotPresent
          name: matomo
          resources:
            limits:
              cpu: 900m
              memory: 2Gi
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 80
              protocol: TCP
          envFrom:
            - secretRef:
                name: env-secrets