apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api-deploy
  name: api-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-deploy
  strategy: {}
  template:
    metadata:
      labels:
        app: api-deploy
        debug: "true"
    spec:
      containers:
      - image: revision-ai/api:latest
        imagePullPolicy: IfNotPresent
        name: api
        ports:
        - containerPort: 8080
          protocol: TCP
        envFrom:
          - configMapRef:
              name: env-config-map
          - secretRef:
              name: env-secrets
        env:
          - name: RABBITMQ_URL
            valueFrom:
              secretKeyRef:
                name: rabbitmq-default-user
                key: connection_string