apiVersion: v1
kind: Service
metadata:
  name: api-service
  labels:
    app: api-deploy
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: api-deploy