apiVersion: v1
kind: Service
metadata:
  name: api-service
  labels:
    app: api-deploy
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app: api-deploy