apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api-deploy
  name: api-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-deploy
  strategy: {}
  template:
    metadata:
      labels:
        app: api-deploy
        debug: "true"
    spec:
      initContainers:
        - name: wait-for-rabbitmq
          image: busybox:latest
          imagePullPolicy: IfNotPresent
          command: ['sh', '-c', 'until nc -z -v -w30 rabbitmq 5672; do echo "Waiting for RabbitMQ..."; sleep 5; done']
        - name: wait-for-mongodb
          image: busybox:latest
          imagePullPolicy: IfNotPresent
          command: ['sh', '-c', 'until nc -z -v -w30 mongodb-svc.mongodb 27017; do echo "Waiting for MongoDB..."; sleep 5; done']

      containers:
        - image: revision-ai/api:latest
          imagePullPolicy: IfNotPresent
          name: api
          resources:
            limits:
              cpu: 800m
              memory: 700Mi
            requests:
              cpu: 200m
              memory: 200Mi
          ports:
            - containerPort: 3000
              protocol: TCP
          envFrom:
            - configMapRef:
                name: env-config-map
            - secretRef:
                name: env-secrets
          env:
            - name: RABBITMQ_URL
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-default-user
                  key: connection_string