apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: file-parser-deploy
  name: file-parser-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: file-parser-deploy
  strategy: {}
  template:
    metadata:
      labels:
        app: file-parser-deploy
        debug: "true"
    spec:
      containers:
      - image: revision-ai/file-parser:latest
        imagePullPolicy: IfNotPresent
        name: file-parser
        envFrom:
          - configMapRef:
              name: env-config-map
          - secretRef:
              name: env-secrets
        env:
          - name: RABBITMQ_URL
            valueFrom:
              secretKeyRef:
                name: rabbitmq-default-user
                key: connection_string