apiVersion: v1
kind: Service
metadata:
  name: frontend-nginx-service
  labels:
    app: frontend-nginx-deploy
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 80
      protocol: TCP
  selector:
    app: frontend-nginx-deploy