apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: quiz-generator-servicemonitor
  labels:
    release: prometheus 
spec:
  jobLabel: quiz-generator
  selector:
    matchLabels:
      app: quiz-generator-deploy
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: prometheus  # service port name in quiz-generator svc
      interval: 30s
      path: /metrics