apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: quiz-generator-deploy
  name: quiz-generator-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: quiz-generator-deploy
  strategy: {}
  template:
    metadata:
      labels:
        app: quiz-generator-deploy
        debug: "true"
    spec:
      initContainers:
        - name: wait-for-rabbitmq
          image: busybox:latest
          imagePullPolicy: IfNotPresent
          command: ['sh', '-c', 'until nc -z -v -w30 rabbitmq 5672; do echo "Waiting for RabbitMQ..."; sleep 5; done']
        - name: wait-for-mongodb
          image: busybox:latest
          imagePullPolicy: IfNotPresent
          command: ['sh', '-c', 'until nc -z -v -w30 mongodb-svc.mongodb 27017; do echo "Waiting for MongoDB..."; sleep 5; done']
      containers:
        - image: revision-ai/quiz-generator:latest
          imagePullPolicy: IfNotPresent
          name: quiz-generator
          ports:
          - containerPort: 9090
            protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 800m
              memory: 1Gi
          envFrom:
            - configMapRef:
                name: env-config-map
            - secretRef:
                name: env-secrets
          env:
            - name: RABBITMQ_URL
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-default-user
                  key: connection_string