name: services-test.yml
on:
    pull_request:
        types: [ opened, synchronize, reopened ]

jobs:
  test:
    name: Run backend tests
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: services

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
            node-version: 22

      - name : run test
        run : sh scripts/tests.sh